# Generated by Django 5.2 on 2025-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginIdCred',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.TextField(blank=True, null=True)),
                ('login_password', models.TextField(blank=True, null=True)),
                ('login_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_id_cred',
            },
        ),
    ]
