# Generated by Django 5.2 on 2025-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_fun', '0002_exportregester'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportregester',
            name='cretated_date_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
