# Generated by Django 5.2 on 2025-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_fun', '0003_exportregester_cretated_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.TextField(blank=True, null=True)),
                ('exposure_type', models.TextField(blank=True, null=True)),
                ('exposure_input_date', models.TextField(blank=True, null=True)),
                ('po_date', models.TextField(blank=True, null=True)),
                ('bl_date', models.TextField(blank=True, null=True)),
                ('collection_date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('adjustment_amount', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('budget_rate', models.TextField(blank=True, null=True)),
                ('hedged_amount', models.TextField(blank=True, null=True)),
                ('invoice_no', models.TextField(blank=True, null=True)),
                ('po_no', models.TextField(blank=True, null=True)),
                ('party_name', models.TextField(blank=True, null=True)),
                ('bank', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('forward_contract_no', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('booked_forward_rate', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('cretated_date_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export_register',
            },
        ),
        migrations.CreateModel(
            name='ImportRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.TextField(blank=True, null=True)),
                ('budget_rate', models.TextField(blank=True, null=True)),
                ('exposure_type', models.TextField(blank=True, null=True)),
                ('exposure_input_date', models.TextField(blank=True, null=True)),
                ('po_date', models.TextField(blank=True, null=True)),
                ('bl_date', models.TextField(blank=True, null=True)),
                ('due_date', models.TextField(blank=True, null=True)),
                ('collection_date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('hedged_amount', models.TextField(blank=True, null=True)),
                ('po_no', models.TextField(blank=True, null=True)),
                ('party_name', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('booked_forward_rate', models.TextField(blank=True, null=True)),
                ('bank', models.TextField(blank=True, null=True)),
                ('forward_contract_no', models.TextField(blank=True, null=True)),
                ('invoice_no', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('cretated_date_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_register',
            },
        ),
        migrations.DeleteModel(
            name='ExportRegester',
        ),
    ]
